# Generated by Django 5.2.3 on 2025-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('slug', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
